name: Database rollback test

on:
 

 workflow_dispatch:

jobs:
  run_migration_test:
    name: Run Flyway migration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run database migrations against prod backup
        run: ./rollback-test-prod.sh
        env:
          SPAWNCTL_ACCESS_TOKEN: ${{ secrets.SPAWNCTL_ACCESS_TOKEN }}
